minecraft_version: "26.1.2"
fabric_loader_version: "0.19.2"
pack_name: "JLN-HUT Modpack"
pack_version: "1.0.0"
mods:
  - name: "Inventory Profiles Next"
    modrinth_project_id: "O7RBXm3n"
    modrinth_version_id: "zpR48YPf"
    file: "InventoryProfilesNext-fabric-26.1-2.3.1.jar"
    url: "https://cdn.modrinth.com/data/O7RBXm3n/versions/zpR48YPf/InventoryProfilesNext-fabric-26.1-2.3.1.jar"
    env: {client: required, server: unsupported}
  - name: "Shoulder Surfing Reloaded"
    modrinth_project_id: "kepjj2sy"
    modrinth_version_id: "QD3tQa99"
    file: "ShoulderSurfing-Fabric-26.1.2-4.22.7.jar"
    url: "https://cdn.modrinth.com/data/kepjj2sy/versions/QD3tQa99/ShoulderSurfing-Fabric-26.1.2-4.22.7.jar"
    env: {client: required, server: unsupported}
  - name: "Fabric API"
    modrinth_project_id: "P7dR8mSH"
    modrinth_version_id: "dZsorAUN"
    file: "fabric-api-0.147.0+26.1.2.jar"
    url: "https://cdn.modrinth.com/data/P7dR8mSH/versions/dZsorAUN/fabric-api-0.147.0%2B26.1.2.jar"
    env: {client: required, server: required}
  - name: "Fabric Language Kotlin"
    modrinth_project_id: "Ha28R6CL"
    modrinth_version_id: "2i87JpYj"
    file: "fabric-language-kotlin-1.13.11+kotlin.2.3.21.jar"
    url: "https://cdn.modrinth.com/data/Ha28R6CL/versions/2i87JpYj/fabric-language-kotlin-1.13.11%2Bkotlin.2.3.21.jar"
    env: {client: required, server: required}
  - name: "libIPN"
    modrinth_project_id: "onSQdWhM"
    modrinth_version_id: "gM74eU2L"
    file: "libIPN-fabric-26.1-6.7.1.jar"
    url: "https://cdn.modrinth.com/data/onSQdWhM/versions/gM74eU2L/libIPN-fabric-26.1-6.7.1.jar"
    env: {client: required, server: required}
  - name: "Cloth Config"
    modrinth_project_id: "9s6osm5g"
    modrinth_version_id: "GFM8zh9J"
    file: "cloth-config-26.1.154.jar"
    url: "https://cdn.modrinth.com/data/9s6osm5g/versions/GFM8zh9J/cloth-config-26.1.154.jar"
    env: {client: required, server: required}
  - name: "Forge Config API Port"
    modrinth_project_id: "ohNO6lps"
    modrinth_version_id: "mwAOaKnn"
    file: "ForgeConfigAPIPort-v26.1.4-mc26.1.x-Fabric.jar"
    url: "https://cdn.modrinth.com/data/ohNO6lps/versions/mwAOaKnn/ForgeConfigAPIPort-v26.1.4-mc26.1.x-Fabric.jar"
    env: {client: required, server: required}
