minecraft_version: "1.21.11"
fabric_loader_version: "0.18.4"
pack_name: "JLN-HUT Modpack"
pack_version: "1.0.0"
mods:
  - name: "Inventory Profiles Next"
    modrinth_project_id: "O7RBXm3n"
    modrinth_version_id: "hUyBZiaa"
    file: "InventoryProfilesNext-fabric-1.21.11-2.2.3.jar"
    url: "https://cdn.modrinth.com/data/O7RBXm3n/versions/hUyBZiaa/InventoryProfilesNext-fabric-1.21.11-2.2.3.jar"
    env: {client: required, server: unsupported}
  - name: "Shoulder Surfing Reloaded"
    modrinth_project_id: "kepjj2sy"
    modrinth_version_id: "VIt9lLsi"
    file: "ShoulderSurfing-Fabric-1.21.11-4.22.0.jar"
    url: "https://cdn.modrinth.com/data/kepjj2sy/versions/VIt9lLsi/ShoulderSurfing-Fabric-1.21.11-4.22.0.jar"
    env: {client: required, server: unsupported}
  - name: "Fabric API"
    modrinth_project_id: "P7dR8mSH"
    modrinth_version_id: "i5tSkVBH"
    file: "fabric-api-0.141.3+1.21.11.jar"
    url: "https://cdn.modrinth.com/data/P7dR8mSH/versions/i5tSkVBH/fabric-api-0.141.3%2B1.21.11.jar"
    env: {client: required, server: required}
  - name: "Fabric Language Kotlin"
    modrinth_project_id: "Ha28R6CL"
    modrinth_version_id: "ViT4gucI"
    file: "fabric-language-kotlin-1.13.9+kotlin.2.3.10.jar"
    url: "https://cdn.modrinth.com/data/Ha28R6CL/versions/ViT4gucI/fabric-language-kotlin-1.13.9%2Bkotlin.2.3.10.jar"
    env: {client: required, server: required}
  - name: "libIPN"
    modrinth_project_id: "onSQdWhM"
    modrinth_version_id: "NfmfXRhx"
    file: "libIPN-fabric-1.21.11-6.6.2.jar"
    url: "https://cdn.modrinth.com/data/onSQdWhM/versions/NfmfXRhx/libIPN-fabric-1.21.11-6.6.2.jar"
    env: {client: required, server: required}
  - name: "Cloth Config"
    modrinth_project_id: "9s6osm5g"
    modrinth_version_id: "xuX40TN5"
    file: "cloth-config-21.11.153-fabric.jar"
    url: "https://cdn.modrinth.com/data/9s6osm5g/versions/xuX40TN5/cloth-config-21.11.153-fabric.jar"
    env: {client: required, server: required}
